# NOTE: This file must be installed with `pre-commit install --hook-type pre-commit --hook-type pre-push`

default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    hooks:
      - id: alejandra-system

  - repo: https://github.com/astro/deadnix
    rev: v1.2.1
    hooks:
      - id: deadnix

  - repo: local
    hooks:
      - id: statix-check
        name: statix check
        entry: statix check
        language: system
        files: '.*\.nix$'
        pass_filenames: false

      - id: flake-check
        name: flake check
        entry: nix flake check
        language: system
        files: '.*\.(nix|lock)$'
        pass_filenames: false
        stages: [pre-push]
